# Production branch: main
name = "frontend"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

[vars]
ENV = "development"
DOCUSIGN_PRIVATE_KEY = "HCh1UddB11F3LKkfrixQdgdS1kgLF1IRTcdzgF7Ij/Q="
DOCUSIGN_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAihr5PtCXRVCgjAlOcZi7\n0hX3c+4P2Kmp8Qqv+FFJmMhH0+dHSAqGfCUW8ZRq3jffrWFnPX1cTtGEudVFECLE\nN+nNFSh0Ed699Roly9g6tuvbse/bxOIVljgfMWTtTKbiDTRRj0mcwHekmxdOHu7p\nwMB+7ldF27u479ZtZ8Z7DaHgF37CMNMq1uwx0Px12AE0WzL70eLnXBAlIsotQAiU\ncErpTk7xf4uRcrM4lOX4c/GdkaiASEgNY/BPcWDXRugl0C86WuAYvdYyUMkvBJba\nbwH4tr0bwdjLrDF0DU+WHkJraDY0ESB3XLaYik+8c8U7GbUEyuARm51NvIexOswL\nowIDAQAB\n-----END PUBLIC KEY-----"
DOCUSIGN_INTEGRATION_KEY = "167c3ccd-56ce-4822-872f-711c5193f292"
DOCUSIGN_IMPERSONATED_USER = "94712e80-4047-4d32-b2db-4fad83b0eb66"
DOCUSIGN_ACCOUNT_ID = "94712e80-4047-4d32-b2db-4fad83b0eb66"
DOCUSIGN_BASE_URL = "https://demo.docusign.net"
X_API_KEY = "AAAAAAAAAAAAAAAAAAAAAG8I7QEAAAAAxLDUL92xFkSJFxm0QkuVV%2BsdyDE%3DyhKNXYFIXQzUaVfozWNgPirOdH1LKzNg89JdZPzUrxGtcajfnp   JA8gjyhuPpKELdPsAeinvyUXm    CbwhkbvKm6j4yp2Zau4kW25UKb5lBAoIVxfFmBy0VV8JAtSBcj   2016308095211708416-xdjc60F9PCVniaegmmJCnSpWNdDtaD    2lgXtAtSORdp4rFYJt0d3FKrMRAljKgUS13bSEd8GG6Ku"


[[d1_databases]]
binding = "DB"
database_name = "ross_tax_prep_db"
database_id = "1be0402b-4c51-4a06-a662-cec3514ce6cc"
